version: '3.8'

networks:
  app:
    name: app

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - app

  php:
    build:
      context: ./docker/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app

  artisan:
    build:
      context: ./docker/php
    container_name: artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - app

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: transactionapi
      MYSQL_USER: api
      MYSQL_PASSWORD: secret@API
      MYSQL_ROOT_PASSWORD: secret@API
    networks:
      - app