version: '3.8'

networks:
  app:
    name: app

services:
  nginx:
    image: galloaleonardo/nginx-stable
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - app

  php:
    image: galloaleonardo/php-fpm-8.0.5:latest
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app

  artisan:
    image: galloaleonardo/php-fpm-8.0.5:latest
    container_name: artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]
    networks:
      - app

  queue-work:
    image: galloaleonardo/php-fpm-8.0.5:latest
    container_name: queue-work
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan", "queue:work" ]
    networks:
      - app

  test:
    image: galloaleonardo/php-fpm-8.0.5:latest
    container_name: test
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan", "test" ]
    networks:
      - app

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    restart: unless-stopped
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: transactionapi
      MYSQL_USER: api
      MYSQL_PASSWORD: secret@API
      MYSQL_ROOT_PASSWORD: secret@API
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - app